# Generated by Django 2.2.6 on 2019-10-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_id', models.IntegerField(db_index=True)),
                ('show_img', models.ImageField(default='', upload_to='show_images')),
                ('blog_img', models.ImageField(default='', upload_to='full_images')),
                ('title', models.CharField(default='', max_length=300)),
                ('content', models.TextField(default='')),
                ('key', models.CharField(default='-1', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=30)),
                ('lname', models.CharField(default='', max_length=30)),
                ('email', models.CharField(default='', max_length=50)),
                ('passwd', models.CharField(default='', max_length=30)),
                ('fblogs', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
