# Generated by Django 2.2.6 on 2019-10-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20191028_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_id',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_img',
        ),
    ]
