# Generated by Django 2.2.6 on 2019-11-01 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20191028_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='verified',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
