# Generated by Django 2.2.6 on 2019-11-07 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_users_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='verified',
            field=models.CharField(default='N', max_length=6),
        ),
    ]
